[build]
    command = "yarn build"
    publish = ".next"

[build.environment]
    NODE_VERSION = "20.19.4"

[[plugins]]
    package = "@netlify/plugin-nextjs"
    
[[headers]]
  for = "/api/labs/mcp-tools/*"
  [headers.values]
    Cache-Control = "no-cache"